
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /
  api-docs:
    path: /api-docs

spring:
  datasource:
    url: ${DATA_SOURCE_URL}
    username: ${DATA_SOURCE_USERNAME}
    password: ${DATA_SOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 4
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: false
      show-sql: false
      properties:
        hibernamte:
          format_sql: false
          dialect: org.hibernate.dialect.PostgreSQLDialect
          default_batch_fetch_size: 1000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

jwt:
  secret: ${JWT_SECRET}

cloud:
  aws:
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2

narea-mall:
  aws:
    s3:
      bucketName: narea-mall-develop